language: csharp

sudo: false  # use the new container-based Travis infrastructure 

dotnet: 2.1.500

install:
  # workaround for missing .net 4.6.1 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.6.1-api/

script:
  - ./build.sh

branches:
 only:
  - master

