os: Visual Studio 2015

init:
  - git config --global core.autocrlf input

branches:
  only:
    - master

build_script:
  - ps: dotnet --info
  - cmd: .\build.cmd

test: off

artifacts:
  - path: bin
    name: Console Application Artifacts

  - path: packaging\*.nupkg
    name: NuGet packages

deploy:
  - provider: NuGet
    api_key:
      secure: B5w2/65WZ+KmwYdfBa+p6L5Bs9T+BxlL/5qz9UP/9G9D1hUFo10Md02XhArMRO9T
    skip_symbols: true
    artifact: packaging\*.nupkg
    on:
      branch: master