name: .NET 5.0

on: [push, pull_request]

jobs:
  buildAndTest:

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
        dotnet: [5.0.202]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and run tests
      run: dotnet fake build -t Test
    - name: Run FSharpLint on itself
      run: |
        cd ./src/FSharpLint.Console
        dotnet run --framework net5.0 lint ../FSharpLint.Core/FSharpLint.Core.fsproj
        dotnet run --framework net5.0 lint ./FSharpLint.Console.fsproj
